services:
  - type: web
    name: telegram-bot
    env: node
    buildCommand: npm install
    startCommand: node main.js
    healthCheckPath: /status
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
